### PR TITLE
Fix/reenable zkpylons functional testing

### LINKED ISSUE #416: proposal submission validation broken on mobile/phone
New proposal form (templates/proposal/form.mako) lists a box for speaker mobile phone, person.mobile
Validation (controllers/proposal.py) lists phone as required in NewPersonSchema, mobile is missing

This leads to an error, unexpected field person.mobile, on submission

### PR DESCRIPTION
**Pull request by lod**
Code base had some old automated functional tests which hadn't been maintained over the years.

I rewrote the test framework so that it was less scary and worked.
I updated and deleted tests where it was obviously appropriate.
I raised issues (#413, #419) on some of these issues where it was less obviously appropriate.

I made some limited changes to the main code base, either to fix minor faults that the testing exposed, fix broken HTML so that tests can parse the output, or change behaviour to allow automated testing.

This fixes #416, #417, #418
This provides tests for #414, #415

I make no statement about the coverage or appropriateness of these tests.
This change set is designed to set a base from which the tests can be improved and maintained.

### CODE REVIEW

**Comment by lod** [comment]
With the updated master this still passes all tests and cleanly applies on my box.

**Comment by jhesketh** [comment]
What's with the lca_info.py.functional_test?

I want to merge this in before we do more work, but it's quite a large change. Most of it is tests so they don't matter, but I'm confused by the template changes. Why do we need to reference fields like 'personphone' rather than 'person.phone'?

Have you tested this by hand?

**Comment by lod** [comment]
The template changes were driven by the test html parser struggling with the broken html. The checker still throws errors but I fixed most of the structural ones so the tests work.

The label reference changes are because the for attribute in label refers to the id of the input element. The input elements have a name of person.phone but an id of personphone. A few of the labels such as radio boxes I removed the for link entirely as linking it to a specific option isn't what we wanted. And yes, I checked it by hand.

lca_info.py.functional_test is an artefact of when the tests had to work with lca_info and I forgot to remove it. I'm pushing a commit to pull it out now.

**Comment by lod** [comment]
Forgot to mention this fixes the big daddy testing bug #379

**Pull request merged**
