### PR TITLE
Merge lca2016

### PR DESCRIPTION
**Pull request by iseppi**
* Merge lca2016 theme
 * An alembic revision has replaced the changes to zk/model/db_content.py (If there is already a row in the db_content_type table with a name of Banner you will need to stamp to revision 3b5c7d3c8366
 * Changes to zkpylons/controllers/person.py and zkpylons/controllers/proposal.py have been excluded from this merge

### CODE REVIEW

**Comment by iseppi** [comment]
I didn't merge zkpylons/controllers/person.py because it could cause a regression if you're not using the lca2016 theme.

I didn't merge zkpylons/controllers/proposal.py because I wasn't entirely sure what was being changed and why. @noisymime are you able to provide more information on what was being fixed?

**Comment by lod** [comment]
Commit 63f9193bba3f3cf8372fc90491286494563ed2df to proposal.py fixes #416, which will conflict with my almost identical fix in #420 (*dramatic sigh*).

I'm not sure of the other work, it looks like 4 commits in total, most refer to editing an existing proposal. If @noisymime could document the issues I volunteer to write functional tests to cover them.

**Comment by iseppi** [comment]
I'm going to merge this tonight, unless there are any objections.

**Comment by jhesketh** [comment]
Looks good to me too

**Pull request merged**
